# file: mysql/tasks/configure.yml

- name: MySQL | Update my.cnf
  template:
    src: etc_mysql_my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: "{{ mysql_root_user }}"
    group: "{{ mysql_root_user }}"
    mode: 0644
  notify:
    - restart mysql