# file: mysql/tasks/secure.yml

- name: MySQL | Set the root password.
  mysql_user:
    name: "{{ mysql_root_user }}"
    password: "{{ mysql_root_password }}"
    host: "127.0.0.1"

- name: MySQL | Configure MySql for easy access as root user
  template:
    src: root_dot_my.cnf.j2
    dest: /root/.my.cnf
    owner: "{{ mysql_root_user }}"
    group: "{{ mysql_root_user }}"
    mode:  0644

- name: MySQL | Delete the anonymous MySQL server user for localhost
  mysql_user:
    user: ""
    state: absent

- name: MySQL | Secure the MySQL root user for IPV6 localhost (::1)
  mysql_user:
    user: "{{ mysql_root_user }}"
    password: "{{ mysql_root_password }}"
    host: "::1"

- name: MySQL | Secure the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user:
    user: "{{ mysql_root_user }}"
    password: "{{ mysql_root_password }}"
    host: "127.0.0.1"

- name: MySQL | Remove the MySQL test database
  mysql_db:
    db: test
    state: absent
